version: "3"
services:
    antibox:
        image: mortea15/antibox
        container_name: antibox
        env_file:
            - list.env

    antibox_cron:
        image: mortea15/antibox:cron
        container_name: antibox_cron
        restart: always
        env_file:
            - list.env
